/**
 * Created by Jingle on 2018/3/19.
 */
export const REQUEST_DATA = 'REQUEST_DATA';

export const RECEIVE_DATA = 'RECEIVE_DATA';

export const TRIGGER_SEARCH = 'TRIGGER_SEARCH';

export const RESET_SEARCH = 'RESET_SEARCH';

export const UPDATE_WECHAT_MENU = 'UPDATE_WECHAT_MENU';

export const DELETE_WECHAT_MENU = 'DELETE_WECHAT_MENU';

export const HANDLE_WECHAT_ARTICLE_ATTRIBUTE = 'HANDLE_WECHAT_ARTICLE-ATTRIBUTE'


